// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication13.Models;

namespace WebApplication13.Migrations
{
    [DbContext(typeof(SDbContext))]
    partial class SDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication13.Models.CourseName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseTimeId");

                    b.Property<string>("Names");

                    b.HasKey("Id");

                    b.HasIndex("CourseTimeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WebApplication13.Models.CourseTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("WebApplication13.Models.CourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseNameId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CourseNameId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("WebApplication13.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseTypeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WebApplication13.Models.CourseName", b =>
                {
                    b.HasOne("WebApplication13.Models.CourseTime", "CourseTime")
                        .WithMany()
                        .HasForeignKey("CourseTimeId");
                });

            modelBuilder.Entity("WebApplication13.Models.CourseType", b =>
                {
                    b.HasOne("WebApplication13.Models.CourseName", "CourseName")
                        .WithMany()
                        .HasForeignKey("CourseNameId");
                });

            modelBuilder.Entity("WebApplication13.Models.Student", b =>
                {
                    b.HasOne("WebApplication13.Models.CourseType", "CourseType")
                        .WithMany()
                        .HasForeignKey("CourseTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
